# POST Request to Create a New Account
POST /accounts
Host: localhost:8080
Content-Type: application/json

{
  "accountId": "user1",
  "accountPassword": "12345",
  "email": "user1@example.com",
  "name": "user1",
  "joinDate": "2024-01-25T15:50:12",
  "lastLoginDate": "2024-01-25T15:50:12",
  "accountStatus": {
    "accountStateId": 2
  }

}

###

POST /login
Host: localhost:8080
Content-Type: application/json

{
"id": "admin",
"pwd": "12345"

}